# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://fuding.qicp.vip:6066/school_wall?useUnicode=true&useSSL=false&character_set_server = utf8mb4 &serverTimezone=Asia/Shanghai
    username: root
    password: v83NwTHzb5_

  jackson:
    default-property-inclusion: non_null # 全局jackson配置

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 3000

