# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_wall?useUnicode=true&useSSL=false&character_set_server = utf8mb4 &serverTimezone=Asia/Shanghai
    username: fuding
    password: Fuding$$$

  jackson:
    default-property-inclusion: non_null # 全局jackson配置

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 3000

