# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_wall_china?useUnicode=true&useSSL=false&character_set_server = utf8mb4 &serverTimezone=Asia/Shanghai
    username: fuding
    password: Fuding$$$

  jackson:
    default-property-inclusion: non_null # 全局jackson配置

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 3000

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
schoolwall:
  jwt:
    # 加密秘钥
    secret: 4a927e2d67e76622fcdf98f2aa4f06fc
    # token有效时长，7天，单位毫秒
    expire: 604800000
    header: Authorization
