CREATE TABLE `sw_posts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `author` bigint(20) unsigned NOT NULL DEFAULT 0,
  `date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `content` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'publish',
  `comment_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `ping_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  #`post_password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  #`post_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  #`to_ping` text COLLATE utf8mb4_unicode_ci NOT NULL,
  #`pinged` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  #`post_content_filtered` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  #`post_parent` bigint(20) unsigned NOT NULL DEFAULT 0,
  `guid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  #`menu_order` int(11) NOT NULL DEFAULT 0,
  `type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'post',
  #`post_mime_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `total_comments` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  #KEY `post_name` (`post_name`(191)),
  KEY `type_status_date` (`type`,`status`,`date`,`id`),
  #KEY `post_parent` (`post_parent`),
  KEY `author` (`author`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;